### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by Robert-Frampton** [eduardolundgren/metal-event-simulator#1]
Hey @jbalsas @brunobasto 

I talked with @mairatma and it looks like this package isn't in use (not even published to npm), and it had some weird edge cases when she tried implementing it. There are also some similar methods in `metal-dom` for simulating events.

I'm fine with deleting this repo, and other metal repos that may not be in use. What do you guys think?

**Comment by eduardolundgren** [comment]
Agreed. Moved to my user, then after a while will delete it. Thanks.

**Comment by jbalsas** [comment]
Too late to the party, but I agree, and I like that we didn't outright delete it, but kept it around. 

For others, and so @eduardolundgren doesn't need to fill up its user with trash repos, can't we have a process for this?
- Update the `README.md` in a repo with a [deprectaed badge](https://github.com/badges/stability-badges#stability-0---deprecated) and a *Removal Date*
- Delete it once the date has been reached :)

**Comment by eduardolundgren** [comment]
We could do the badge. In this specific case it wasn't even published to npm, nobody theoretically was using it. Do you want move this one back with the badge?

**Comment by jbalsas** [comment]
nah, it's fine :)
